site_name: My Docs
theme:
  name: 'material'
nav:
    - Home: index.md
    - iOS: 
      - 简单的计算器实现: iOS/简单的计算器.md
      - NSObject,NSProxy以及异常处理: iOS/NSObject,NSProxy以及异常处理.md
    - 智能家居:
      - BLE的底层原理: 智能家居/BLE的底层原理.md
    - 翻译:
      - AppleScript语言介绍: 翻译/AppleScript语言介绍.md
      - BLE技术介绍: 翻译/BLE技术介绍.md
    - 读书笔记:
      - 《程序开发心理学》第一篇: 读书笔记/《程序开发心理学》第一篇.md
      - 《程序开发心理学》第二篇: 读书笔记/《程序开发心理学》第二篇.md
      - 《程序开发心理学》第三篇: 读书笔记/《程序开发心理学》第三篇.md
      - 《程序开发心理学》第四篇: 读书笔记/《程序开发心理学》第四篇.md
      - 《人月神话》笔记: 读书笔记/《人月神话》笔记.md